sensors:
  right_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]

  conv_beam1:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.36, 3.5, 0.88]
      rpy: [0, 0, pi]

  conv_beam2:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.36, 0.8, 0.88]
      rpy: [0, 0, pi]

  conv_camera1:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-0.4, 3.0, 1.8]
      rpy: [pi, pi/2, -pi/2]


  