sensors:
  right_bins_camera:
    type: advanced_logical_camera
    # visualize_fov: true
    pose:
      xyz: [-2.286, 2.96, 1.8]
      rpy: [pi, pi/2, 0]

  left_bins_camera:
    type: advanced_logical_camera
    # visualize_fov: true
    pose:
      xyz: [-2.286, -2.96, 1.8]
      rpy: [pi, pi/2, 0]

  kts1_camera:
    type: advanced_logical_camera
    # visualize_fov: true
    pose:
      xyz: [-1.3, -5.8, 1.8]
      rpy: [pi, pi/2, pi/2]
  
  kts2_camera:
    type: advanced_logical_camera
    # visualize_fov: true
    pose:
      xyz: [-1.3, 5.8, 1.8]
      rpy: [pi, pi/2, -pi/2]

  conv_camera1:
    type: advanced_logical_camera
    visualize_fov: true
    pose:
      xyz: [-0.535492, -4.191316, 1.799998]
      rpy: [pi, pi/2, -pi/2]

  conv_beam1:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.870301, -4.000000, 0.942023]
      rpy: [1.570796, 0.000006, -0.000008]

  conv_beam2:
    type: break_beam
    visualize_fov: true
    pose:
      xyz: [-0.870301, -3.6, 0.942023]
      rpy: [1.570796, 0.000006, -0.000008]

  
  
    